# Generated by Django 5.1.2 on 2024-10-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0008_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
