# Generated by Django 5.1.2 on 2024-10-21 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0012_alter_post_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='likedposts', through='a_posts.LikedPost', to=settings.AUTH_USER_MODEL),
        ),
    ]
