name: Awesome Testing
on:
  pull_request:
    branches:
    - staging
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT : development
      SECRET_KEY : secret_key
      ENCRYPT_KEY : WeP6BqBm5Fj9ZAkoQoy4E_sLGSdaMSKo6RFeBr_c_wc=
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12.6
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements.txt
      - run: python manage.py test
